/* ============================================================
   Muskan Gupta — Experience records, technical skills, craft data
   Every record is drawn from the résumé; wording restructured into
   Situation → Action → Result, plus a technical-build note that
   names the tools used. Edit here, the site renders it.
   ============================================================ */
window.CAPS = {
  climate:    'Climate risk',
  reporting:  'Reporting & regulation',
  carbon:     'Carbon accounting',
  strategy:   'Decarbonization strategy',
  leadership: 'Leadership & IP',
  audit:      'Audit & QA',
  analytics:  'Analytics & tooling'
};

window.FIRMS = [
  { key: 'deloitte', name: 'Deloitte India', short: 'Deloitte', loc: 'Gurugram, Haryana', span: 'Feb 2024 — Present', color: '#86bc25', roles: [{ title: 'Deputy Manager', when: 'Jun 2025 — Present', current: true }, { title: 'Assistant Manager', when: 'Feb 2024 — May 2025' }] },
  { key: 'kpmg', name: 'KPMG Global Services', short: 'KPMG', loc: 'Gurugram, Haryana', span: 'Mar 2023 — Feb 2024', color: '#00338d', roles: [{ title: 'Associate Consultant', when: 'Mar 2023 — Feb 2024' }] },
  { key: 'pwc', name: 'PwC India', short: 'PwC', loc: 'Gurugram, Haryana', span: 'Jun 2022 — Mar 2023', color: '#d04a02', roles: [{ title: 'Consultant', when: 'Jun 2022 — Mar 2023' }] }
];

/* Technical toolkit. `group` drives the two blocks in the hero console;
   `craft` links to the matching tab in the skills section. Levels are
   self-assessed; engagement counts are computed from the records below. */
window.TECH = [
  { key: 'excel', label: 'Advanced Excel', sub: 'Dynamic arrays · LET/LAMBDA · structured tables · data validation', group: 'analytics', level: 'Advanced', craft: 'excel',
    builds: 'Scoring engines, factor databases, attribution models and DNSH matrices built as structured, versioned workbooks other people can audit.',
    evidence: ['Double materiality scoring tool adopted as the Deloitte team standard.', 'EU Taxonomy DNSH matrix with automated PAI quantification for 30+ activities.', 'PCAF financed-emissions model across six funds and 200+ assets.'] },
  { key: 'vba', label: 'VBA macros', sub: 'Modules · UserForms · event-driven audit logging', group: 'automation', level: 'Advanced', craft: 'excel',
    builds: 'Automation layers on top of the workbooks: scoring runs, input forms, change logs written by the macro itself.',
    evidence: ['VBA-automated scoring cut a CSRD double materiality assessment from six weeks to two.', 'Reallocated 40 analyst-hours to strategic advisory on one engagement.'] },
  { key: 'pq', label: 'Power Query & Power Pivot', sub: 'M transformations · data models · DAX measures inside Excel', group: 'automation', level: 'Advanced', craft: 'analytics',
    builds: 'Repeatable data intake: combine client returns, type and clean columns, load into a model instead of pasting.',
    evidence: ['Multi-source activity data and supplier returns consolidated for GHG inventories.', 'Versioned emission factors served to inventory workbooks through the data model.'] },
  { key: 'pbi', label: 'Power BI', sub: 'Star-schema models · DAX · board-ready heatmaps', group: 'analytics', level: 'Advanced', craft: 'analytics',
    builds: 'Board-level risk visuals with scenario and horizon slicers, built on a clean fact-and-dimension model.',
    evidence: ['Climate risk heatmaps across three NGFS scenarios and three horizons for a tyre manufacturer.', 'Informed ₹200Cr+ of capital allocation toward flood resilience and heat adaptation.'] },
  { key: 'python', label: 'Python', sub: 'pandas · NumPy · scripting', group: 'analytics', level: 'Proficient', craft: 'analytics',
    builds: 'Pipelines for the heavy lifting: merge activity data with versioned factors, validate keys, aggregate by scope and category.',
    evidence: ['Emission factor database standardising 2.3M tCO₂e across 10+ Fortune 500 inventories.', 'Calculation time halved; PCAF data quality lifted two tiers.'] },
  { key: 'ppt', label: 'PowerPoint', sub: 'SCQA storylines · action titles · ghost decks · speaker notes', group: 'analytics', level: 'Advanced', craft: 'ppt',
    builds: 'Decks a board can decide on: the storyline first, one argument per slide, evidence in the exhibit, decision at the end.',
    evidence: ['Board strategy deck that carried ₹200Cr+ of adaptation capital.', 'C-suite risk registers that steered $80M of adaptation investment.', 'Case-study decks for an eight-module programme, 50+ consultants.'] },
  { key: 'word', label: 'Word', sub: 'Numbered styles · cross-references · tracked changes · automated tables', group: 'analytics', level: 'Advanced', craft: 'word',
    builds: 'Regulator-grade long-form documents that survive several review rounds without breaking numbering or references.',
    evidence: ['40-page IFRS S1/S2 readiness framework adopted by the Bank of Mauritius.', 'Three supplier decarbonization handbooks adopted across procurement.', 'Methodology documentation reused across three KPMG engagements.'] },
  { key: 'qgis', label: 'QGIS', sub: 'Spatial joins · hazard layers · site exposure', group: 'analytics', level: 'Working', craft: 'analytics',
    builds: 'Site-level exposure work where the answer is spatial: which plant sits in which flood zone or heat band.',
    evidence: ['Physical risk screening for a multi-site manufacturer under three climate scenarios.'] },
  { key: 'ccalc', label: 'CCaLC2', sub: 'Life cycle assessment · product carbon footprints', group: 'analytics', level: 'Working', craft: 'audit',
    builds: 'Cradle-to-gate footprints and benchmarking for product-level decisions.',
    evidence: ['Life cycle assessment of polyethylene and polypropylene supporting GAIL India’s Net Zero plan.'] },
  { key: 'nlp', label: 'NLP regulatory scanning', sub: 'Text mining of standards and regulation · requirement extraction', group: 'automation', level: 'Applied', craft: 'word',
    builds: 'Scan regulatory texts and standards for requirements, then map them against a client’s disclosures.',
    evidence: ['Disclosure gap assessments for 12+ clients against ESRS, IFRS S1/S2 and ASRS.', 'Regulatory landscape mapping for biofuels, plastic waste and pyrolysis oil.'] },
  { key: 'aiqc', label: 'AI-enabled data quality checks', sub: 'Anomaly flags · completeness and unit checks · reviewer prompts', group: 'automation', level: 'Applied', craft: 'audit',
    builds: 'Automated first-pass checks on inventory inputs so senior review time goes to judgement calls, not typos.',
    evidence: ['First-pass accuracy up 30%; senior review down 15 hours a month.'] },
  { key: 'automation', label: 'Workflow automation', sub: 'Scoring runs · attribution · indicator quantification · refresh', group: 'automation', level: 'Advanced', craft: 'excel',
    builds: 'Turning a one-off assessment into a repeatable practice asset that the next team can run.',
    evidence: ['Automated PAI quantification cut EU Taxonomy assessment time by 40%.', 'Automated PCAF attribution halved financed-emissions calculation time.', 'Four tools adopted as team or client standards.'] }
];

window.ENGAGEMENTS = [
  { id: 'dma-poland', firm: 'deloitte', caps: ['reporting', 'analytics'], tech: ['excel', 'vba', 'pq', 'automation'], title: 'CSRD double materiality for a Polish manufacturer',
    situation: 'First CSRD cycle: 28 candidate topics and 150+ data points to assess on a six-week timeline.',
    action: 'Led the workstream, designed weighted impact and financial scoring, and built a VBA-automated Excel tool with thresholds and an audit trail.',
    result: 'Delivered in two weeks. The tool was adopted as the team standard and 40 analyst-hours were redirected to strategic advisory.',
    build: 'Excel scoring engine on a structured table with named threshold and weight ranges; VBA RunScoring() macro writes every run to an audit-log sheet; Power Query consolidates the 150+ data points from stakeholder returns.',
    metrics: [{ v: '67%', l: 'faster delivery' }, { v: '28', l: 'topics scored' }, { v: '40h', l: 'reallocated' }], tools: ['CSRD', 'ESRS'], post: 'double-materiality-sounds-simple' },
  { id: 'tyre-climate-risk', firm: 'deloitte', caps: ['climate', 'analytics'], tech: ['pbi', 'excel', 'ppt', 'qgis'], title: 'Board-level climate risk for a leading Indian tyre manufacturer',
    situation: 'Transition and physical exposure across sites had never been quantified for the board.',
    action: 'Directed the workstream: modelled SSP1-2.6, SSP2-4.5 and SSP3-8.5 across three horizons, then built Power BI heatmaps and a board strategy deck.',
    result: 'Informed ₹200Cr+ of capital allocation toward flood resilience and heat adaptation.',
    build: 'Scenario model in Excel (three pathways × three horizons per site) feeding a Power BI star schema with DAX measures for retained cost and exposure rank; site hazard layers checked spatially; SCQA board deck with action titles.',
    metrics: [{ v: '₹200Cr+', l: 'capital informed' }, { v: '3 × 3', l: 'scenarios × horizons' }], tools: ['NGFS', 'TCFD / IFRS S2'], post: 'the-resolution-gap' },
  { id: 'fmcg-eudr', firm: 'deloitte', caps: ['reporting', 'strategy'], tech: ['excel', 'ppt'], title: 'EUDR and PPWR readiness for a global FMCG client',
    situation: 'Deforestation and packaging rules threatened EU market access across a deep supplier base.',
    action: 'Mapped traceability across 12 supplier tiers, identified eight circularity gaps and sequenced a phased compliance roadmap.',
    result: 'The client approved a €1.5M supply chain investment on the strength of the roadmap.',
    build: 'Tier-by-tier traceability register in Excel with gap scoring per requirement; phased roadmap and investment case presented as a decision deck.',
    metrics: [{ v: '€1.5M', l: 'investment secured' }, { v: '12', l: 'supplier tiers' }, { v: '8', l: 'gaps identified' }], tools: ['EUDR', 'PPWR', 'Supply chain traceability'], post: 'ppwr-packaging-market-access' },
  { id: 'ef-database', firm: 'deloitte', caps: ['carbon', 'analytics'], tech: ['python', 'excel', 'pq', 'automation'], title: 'Emission factor database for GHG inventories',
    situation: 'Every inventory rebuilt factors by hand, with inconsistent PCAF data quality across 10+ Fortune 500 clients in semiconductors, automotive and BFSI.',
    action: 'Built a Python/Excel database with versioned factors and automated Scope 1, 2 and 3 calculations.',
    result: 'Standardised 2.3M tCO₂e, lifted PCAF data quality by two tiers and halved calculation time.',
    build: 'pandas pipeline merges activity data with release-tagged factors (validated many-to-one), aggregates by scope and category; Excel front-end refreshes through Power Query so analysts never paste factors again.',
    metrics: [{ v: '2.3M', l: 'tCO₂e standardised' }, { v: '−50%', l: 'calculation time' }, { v: '+2', l: 'PCAF quality tiers' }], tools: ['GHG Protocol', 'PCAF'], post: 'every-problem-leads-to-the-supply-chain' },
  { id: 'eu-taxonomy-fund', firm: 'deloitte', caps: ['reporting', 'analytics'], tech: ['excel', 'automation'], title: 'EU Taxonomy alignment for a European investment fund',
    situation: '30+ economic activities needed do-no-significant-harm screening and principal adverse impact quantification.',
    action: 'Built an Excel DNSH scoring matrix with automated PAI indicator quantification.',
    result: 'Assessment time fell 40% versus manual benchmarking.',
    build: 'Activity × criterion DNSH matrix with lookup-driven thresholds and automated PAI indicator calculations; one input sheet, one output sheet, no manual re-keying.',
    metrics: [{ v: '−40%', l: 'assessment time' }, { v: '30+', l: 'activities screened' }], tools: ['EU Taxonomy', 'SFDR'] },
  { id: 'verra-feasibility', firm: 'deloitte', caps: ['carbon'], tech: ['excel', 'word'], title: 'Verra VM0042 carbon credit feasibility for an agricultural client',
    situation: 'The client needed to know whether soil-carbon credits were financially viable before investing.',
    action: 'Validated a 12,000 tCO₂e baseline and additionality through leakage assessments.',
    result: 'Confirmed viability for $500K+ in annual credit revenue.',
    build: 'Baseline and leakage quantification model in Excel with scenario toggles for price and permanence; feasibility memo structured against the VM0042 methodology requirements.',
    metrics: [{ v: '$500K+', l: 'annual credit revenue' }, { v: '12,000', l: 'tCO₂e baseline' }], tools: ['Verra VCS', 'VM0042'], post: 'two-nbs-projects-only-one-holds-value' },
  { id: 'analyst-qa', firm: 'deloitte', caps: ['leadership', 'audit'], tech: ['excel', 'aiqc', 'word'], title: 'Analyst coaching and QA protocols',
    situation: 'GHG inventories and disclosure assessments were consuming senior review time on avoidable errors.',
    action: 'Coached three analysts per engagement and established QA protocols for calculations and disclosure assessments.',
    result: 'First-pass accuracy rose 30% and senior review time fell by 15 hours a month.',
    build: 'Tie-out and variance checklists in Excel with tolerance thresholds; AI-assisted completeness and unit checks on inputs before human review; written protocol with sign-off steps.',
    metrics: [{ v: '+30%', l: 'first-pass accuracy' }, { v: '−15h', l: 'senior review a month' }], tools: ['QA protocols', 'Review checklists'] },
  { id: 'bom-framework', firm: 'deloitte', caps: ['reporting', 'climate'], tech: ['word', 'excel'], title: 'IFRS S1/S2 readiness framework for the Bank of Mauritius',
    situation: 'The regulator needed a consistent way to assess eight local banks against the ISSB standards.',
    action: 'Authored a 40-page framework evaluating readiness across three transition pathways.',
    result: 'Formally adopted by the regulator and cited in national sustainable finance policy guidance.',
    build: 'Word document with numbered heading styles, cross-referenced requirements and tracked changes through every review round; bank-by-bank readiness scoring maintained in an Excel workbook behind the tables.',
    metrics: [{ v: 'Adopted', l: 'by the regulator' }, { v: '8', l: 'banks assessed' }, { v: '40', l: 'pages' }], tools: ['IFRS S1/S2', 'Transition pathways'], post: 'ecb-climate-factor-collateral' },
  { id: 'esg-programme', firm: 'deloitte', caps: ['leadership'], tech: ['ppt', 'word'], title: 'Eight-module ESG capability programme',
    situation: '50+ consultants needed a shared foundation in BRSR Core, IFRS S1/S2, double materiality and climate risk.',
    action: 'Designed the programme and created reusable case-study IP for each module.',
    result: '85% knowledge retention and new-hire ramp-up about three weeks faster.',
    build: 'Eight case-study decks with a consistent visual grammar and facilitator notes; written case packs and answer keys as reusable IP.',
    metrics: [{ v: '50+', l: 'consultants' }, { v: '85%', l: 'retention' }, { v: '−3 wks', l: 'ramp-up' }], tools: ['BRSR Core', 'IFRS S1/S2', 'Case-study IP'] },
  { id: 'gap-assessments', firm: 'deloitte', caps: ['reporting', 'audit'], tech: ['excel', 'nlp', 'word'], title: 'ESG disclosure gap assessments for 12+ clients',
    situation: 'Clients reporting under mixed frameworks needed to know their distance from ESRS, IFRS S1/S2 and ASRS.',
    action: 'Cross-mapped GRI, SASB, TCFD and CDP disclosures against the target standards.',
    result: '25+ improvement areas identified per client.',
    build: 'Requirement libraries extracted from the standards with NLP-assisted scanning, cross-mapped in an Excel matrix (requirement × framework × client evidence); gap reports generated from the matrix.',
    metrics: [{ v: '12+', l: 'clients' }, { v: '25+', l: 'improvement areas each' }], tools: ['ESRS', 'IFRS S1/S2', 'GRI', 'SASB', 'TCFD', 'CDP'], post: 'double-materiality-identified-but-used' },

  { id: 'pcaf-model', firm: 'kpmg', caps: ['carbon', 'analytics'], tech: ['excel', 'automation'], title: 'Financed emissions for a $1.8B AUM asset manager',
    situation: 'Six funds and 200+ assets with no consistent attribution or data-quality view.',
    action: 'Built an Excel model automating PCAF attribution and data-quality scoring from 1 to 5.',
    result: 'Calculation time halved; portfolio-level decarbonization target setting enabled.',
    build: 'Asset-level attribution engine (outstanding ÷ EVIC × company emissions) with PCAF data-quality tiering per asset class, fund roll-ups and a portfolio dashboard sheet.',
    metrics: [{ v: '$1.8B', l: 'AUM covered' }, { v: '200+', l: 'assets' }, { v: '−50%', l: 'calculation time' }], tools: ['PCAF'] },
  { id: 'tech-climate-risk', firm: 'kpmg', caps: ['climate'], tech: ['excel', 'ppt'], title: 'Climate risk registers for a technology conglomerate',
    situation: 'Leadership needed sector-by-sector exposure across four sectors under 1.5°C and 3°C futures.',
    action: 'Applied NGFS scenarios with PESTEL analysis to produce C-suite risk registers.',
    result: 'Directly informed $80M of adaptation investment prioritisation.',
    build: 'Risk registers scored for likelihood and impact per sector and scenario in Excel; C-suite decks built around the prioritised register with one decision per slide.',
    metrics: [{ v: '$80M', l: 'adaptation investment' }, { v: '4', l: 'sectors' }], tools: ['NGFS', 'PESTEL'], post: 'quantifying-climate-risk-start-with-your-numbers' },
  { id: 'supplier-handbooks', firm: 'kpmg', caps: ['strategy', 'carbon'], tech: ['word'], title: 'Supplier decarbonization handbooks',
    situation: 'Procurement needed a practical way to engage suppliers on the client’s science-based targets.',
    action: 'Developed three handbooks covering 20+ technologies, from solar and battery storage to green hydrogen.',
    result: 'Adopted as the standard supplier engagement toolkit across procurement.',
    build: 'Three structured Word handbooks with consistent technology templates (readiness, cost, abatement, next steps), cross-referenced and version-controlled for procurement reuse.',
    metrics: [{ v: '3', l: 'handbooks' }, { v: '20+', l: 'technologies' }], tools: ['SBTi'], post: 'sbti-v2-era-of-implementation' },
  { id: 'methodology-review', firm: 'kpmg', caps: ['leadership', 'audit'], tech: ['word', 'excel'], title: 'Deliverable review and methodology documentation',
    situation: 'Three concurrent engagements needed consistent methods and reviewed outputs.',
    action: 'Reviewed 5+ junior analyst deliverables per quarter and contributed to internal ESG methodology documentation.',
    result: 'Methodology reused across three concurrent engagements.',
    build: 'Review checklists and calculation tie-outs in Excel; methodology documentation with numbered procedures and worked examples.',
    metrics: [{ v: '5+', l: 'reviews a quarter' }, { v: '3', l: 'engagements' }], tools: ['Review protocols'] },

  { id: 'steel-netzero', firm: 'pwc', caps: ['strategy'], tech: ['excel', 'ppt'], title: 'Net zero pathway for a major steel and power producer',
    situation: 'The client needed a credible high-level route to its Net Zero objective.',
    action: 'Supported development of a decarbonization pathway focused on process improvement and technology integration.',
    result: 'Delivered a high-level pathway aligned with the Net Zero objective.',
    build: 'Lever-by-lever abatement and timing model in Excel; pathway storyline and wedge chart in the client deck.',
    metrics: [{ v: 'Net Zero', l: 'pathway' }], tools: ['Decarbonization pathways'] },
  { id: 'oil-gas-roadmap', firm: 'pwc', caps: ['strategy'], tech: ['excel', 'ppt'], title: 'Green transition roadmap for a South Asian oil and gas company',
    situation: 'Emission hotspots and feasible levers had not been mapped against the business outlook.',
    action: 'Identified key emission hotspots and assessed decarbonization levers against available technologies.',
    result: 'Roadmap aligned with the company’s business outlook and technology options.',
    build: 'Hotspot analysis and lever screening in Excel (emissions share, technology readiness, cost); phased roadmap presented as a decision deck.',
    metrics: [{ v: 'Roadmap', l: 'delivered' }], tools: ['Decarbonization levers'] },
  { id: 'biofuels-regulation', firm: 'pwc', caps: ['reporting', 'strategy'], tech: ['word', 'nlp', 'ppt'], title: 'Biofuels and plastic waste regulation for an international oil major',
    situation: 'The client needed clarity on biofuels, plastic waste export and pyrolysis oil regulation, plus available incentives.',
    action: 'Mapped the regulatory landscape and evaluated state government incentives for waste management activities.',
    result: 'Client equipped to weigh the E and S contributions of each option and the incentive routes available.',
    build: 'Regulatory landscape scanned and structured into a requirement-and-incentive register; findings written up with cross-referenced sources and summarised for the client team.',
    metrics: [{ v: 'Regulatory map', l: 'delivered' }], tools: ['Regulatory research'] },
  { id: 'thought-leadership', firm: 'pwc', caps: ['leadership'], tech: ['word', 'ppt'], title: 'Thought leadership and business development',
    situation: 'The practice needed internal competencies and a pipeline in climate finance and carbon markets.',
    action: 'Authored thought leadership on climate finance, carbon markets and offsetting; tracked tenders and developed bid documents.',
    result: 'Built internal competency and supported the practice pipeline.',
    build: 'Long-form thought leadership papers and bid documents in Word; workshop and pitch decks in PowerPoint.',
    metrics: [{ v: 'Climate finance', l: 'thought leadership' }], tools: ['Carbon markets', 'Bid documents'], post: 'offsets-compensate-they-dont-manage' }
];

/* Craft: how the everyday tools are used at an advanced level */
window.CRAFT = [
  { key: 'excel', label: 'Excel', kicker: 'Models that other people can audit',
    lead: 'Scoring engines, factor databases and attribution models built as structured, versioned workbooks rather than one-off spreadsheets.',
    techniques: ['VBA modules and UserForms', 'Power Query (M) pipelines', 'Power Pivot data models', 'DAX measures', 'Dynamic arrays and LET/LAMBDA', 'XLOOKUP and INDEX/MATCH', 'Structured tables and named ranges', 'Data validation and error traps', 'Scenario, sensitivity and goal-seek', 'Change logs and audit trails'],
    evidence: ['VBA double materiality scoring engine: 28 topics, 150+ data points, adopted as the team standard.', 'Emission factor database with versioned factors and automated Scope 1/2/3 calculations for 10+ Fortune 500 inventories.', 'EU Taxonomy DNSH matrix with automated PAI quantification for 30+ activities.', 'PCAF financed-emissions model across six funds and 200+ assets with data-quality scoring.'] },
  { key: 'ppt', label: 'PowerPoint', kicker: 'Decks a board can decide on',
    lead: 'Storyline first, slides second. Action titles carry the argument, exhibits carry the evidence, and every deck ends in a decision.',
    techniques: ['SCQA and pyramid storylines', 'Action titles and executive summaries', 'MECE structure', 'Risk heatmaps, bridges and tracker charts', 'Ghost decks before build', 'Appendix discipline', 'Consistent visual grammar', 'Speaker notes and pre-reads'],
    evidence: ['Board strategy deck and Power BI heatmaps that informed ₹200Cr+ of adaptation capital for a tyre manufacturer.', 'C-suite risk registers under 1.5°C and 3°C scenarios that steered $80M of adaptation investment.', 'Eight-module ESG training programme with case-study decks for 50+ consultants.'] },
  { key: 'word', label: 'Word', kicker: 'Long-form frameworks that survive review',
    lead: 'Regulator-grade documents: numbered structures, cross-referenced requirements, tracked changes through every review round.',
    techniques: ['Style hierarchies and numbered headings', 'Cross-references and automated tables', 'Tracked changes and comment resolution', 'Requirement-to-evidence mapping tables', 'Plain-language executive summaries', 'Version control and sign-off pages'],
    evidence: ['40-page IFRS S1/S2 readiness framework for the Bank of Mauritius, adopted by the regulator and cited in national policy.', 'Three supplier decarbonization handbooks adopted across a procurement function.', 'Internal ESG methodology documentation reused across three concurrent engagements.'] },
  { key: 'audit', label: 'Audit & QA', kicker: 'Numbers that hold under assurance',
    lead: 'Every inventory and disclosure goes through tie-outs, reconciliations, sampling and four-eyes review before a client sees it.',
    techniques: ['Boundary and consolidation checks', 'Emission factor version tie-outs', 'Unit and completeness reconciliations', 'Variance analysis with thresholds', 'Statistical sampling and evidence trails', 'Four-eyes sign-off', 'Cross-framework gap mapping', 'Assurance readiness (BRSR Core, ISO 14064)'],
    evidence: ['QA protocols for GHG inventories and disclosure assessments: first-pass accuracy up 30%, senior review down 15 hours a month.', 'PCAF data quality lifted two tiers through standardised factors.', 'Disclosure gap assessments for 12+ clients against ESRS, IFRS S1/S2 and ASRS, cross-mapped to GRI, SASB, TCFD and CDP.'] },
  { key: 'analytics', label: 'Analytics', kicker: 'Repeatable pipelines, not one-off analyses',
    lead: 'Python for the heavy lifting, Power BI for the boardroom, QGIS where the answer is spatial.',
    techniques: ['Python (pandas, NumPy) pipelines', 'Power BI data models and DAX', 'Power Query (M) transformations', 'NGFS scenario modelling', 'Marginal abatement cost curves', 'QGIS spatial analysis', 'NLP-based regulatory scanning', 'AI-assisted data quality checks', 'CCaLC2 life cycle assessment'],
    evidence: ['Python/Excel emission factor database standardising 2.3M tCO₂e and halving calculation time.', 'Power BI climate risk heatmaps across three scenarios and three horizons.', 'NLP-based regulatory scanning and AI-enabled data quality checks in disclosure work.'] }
];

/* Career timeline (Gantt). Dates are YYYY-MM; 'now' means today. */
window.CAREER = {
  start: '2020-08',
  rows: [
    { label: 'Deloitte India', sub: 'Gurugram', firm: 'deloitte', bars: [
      { kind: 'role', title: 'Assistant Manager', from: '2024-02', to: '2025-05' },
      { kind: 'role', title: 'Deputy Manager', from: '2025-06', to: 'now', current: true } ] },
    { label: 'KPMG Global Services', sub: 'Gurugram', firm: 'kpmg', bars: [ { kind: 'role', title: 'Associate Consultant', from: '2023-03', to: '2024-02' } ] },
    { label: 'PwC India', sub: 'Gurugram', firm: 'pwc', bars: [ { kind: 'role', title: 'Consultant', from: '2022-06', to: '2023-03' } ] },
    { label: 'Internships', sub: 'Research & live projects', bars: [
      { kind: 'intern', title: 'Aseries Envirotek', from: '2021-06', to: '2021-09' },
      { kind: 'intern', title: 'GAIL India', from: '2021-09', to: '2021-12' },
      { kind: 'intern', title: 'Emergent Ventures', from: '2022-02', to: '2022-05' } ] },
    { label: 'Education', sub: 'TERI SAS, New Delhi', bars: [ { kind: 'edu', title: 'MSc Climate Science & Policy', from: '2020-08', to: '2022-05' } ] }
  ]
};
